### ISSUE TITLE
Support for addons

### ISSUE THREAD

**Issue by dustinfarris** [emberwatch/ember-cli-typescript#3]
This isn't ready for addons yet:

I'm not an ember-cli expert, but I'd say these are a few things to address:

- [ ] Including addons and tests/dummy/app in tsconfig
- [ ] exporting addon code to the addon name module (surprised this doesn't happen already)
- [ ] strategy for non-typescript apps to consume typescript addons

**Comment by rwjblue** [comment]
Most of these (I don't know what the first one means) should "just" work if things are setup in this addon properly. 

Have you tested and found an issue?

**Comment by dustinfarris** [comment]
Yeah I think so.  I renamed one of my addon files to .ts just to see, and the module disappeared from the build.

<img width="658" alt="screenshot 2016-12-10 17 48 36" src="https://cloud.githubusercontent.com/assets/1087165/21076731/1b84e3f6-bf01-11e6-838a-ef26e46662ee.png">

It seems to compile fine, no errors from typescript.

**Comment by dustinfarris** [comment]
The first item is in reference to the [includes config](https://github.com/emberwatch/ember-cli-typescript/blob/master/blueprints/ember-cli-typescript/files/tsconfig.json#L14-L16) in the tsconfig blueprint:

```json
"include": [
  "app/**/*"
]
```

Seems geared toward apps not addons.

**Comment by winding-lines** [comment]
For addons you may just want broccoli-typescript-compiler and ember-rollup? Not sure on details. Apps are my focus right now.

Marius
---

**Comment by dustinfarris** [comment]
@winding-lines ok, i didn't realize ember-rollup was working now.  will give that a try, thanks!
