### ISSUE TITLE
Current blueprint does not work for *editor* module resolution

### ISSUE THREAD

**Issue by chriskrycho** [emberwatch/ember-cli-typescript#4]
In order to get module resolution working properly in VS Code—i.e., so that code completion and navigation-to-definition worked—I had to make the following changes to the blueprint. Note the additions to the `paths` and `include` keys.

```json
{
  "compilerOptions": {
    "target": "ES6",
    "allowJs": true,
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "mobile-web/config/*": ["config/*"],
      "mobile-web/tests/*": ["tests/*"],
      "mobile-web/*": ["app/*"],
      "npm:*": ["local-types/*"],
      "*": ["local-types/*"]
    }
  },
  "include": [
    "app/**/*",
    "tests/**/*"
  ]
}
```

If possible, these should either be generated by default, or the README should include them (I'm happy to submit a PR for either change, but wanted to open for discussion). It may also be worth bringing up the specific issue highlighted in the [Configuration file](https://github.com/emberwatch/ember-cli-typescript/blob/9cae86bd36f95174953b8f714f70397e91ea16c3/README.md#configuration-file) section with the TypeScript team, as it seems like it may well affect more than just us.

(I'm concerned from a comment @locks made in Slack that this may end up including the `tests` directory during the processing, but that seems like a decision that should be made _during_ the Broccoli filtering, just like it would be in the pure-JS case, right?)

**Comment by chriskrycho** [comment]
Added the above configuration (sanitized) [to the wiki](https://github.com/emberwatch/ember-cli-typescript/wiki/tsconfig-how-to). We can keep iterating on this over time.

**Comment by martletandco** [comment]
Adding app specific paths fixes my editor but breaks my build. I'm not sure if I'm running different versions of Typescript or broccoli-typescript-compiler, and if that makes a difference

It looks like JavaScript files are getting past the `**/*.ts` filter via type files tree. [`typePaths`](https://github.com/emberwatch/ember-cli-typescript/blob/master/lib/typescript-preprocessor.js#L33) grabs everything out of `config.compilerOptions.paths` and treats it as type info

-- **Several days later** --

I ended up making a PR for this as I'm pretty sure it is a bug: #14
