### ISSUE TITLE
 Cannot find module 'ember-simple-auth/mixins/application-route-mixin'

### ISSUE THREAD

**Issue by theseyi** [emberwatch/ember-cli-typescript#41]
I have a `tsconfig.json` file similar to the following, but 

```javascript
{
  "compilerOptions": {
    "target": "ES6",
    "allowJs": true,
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noEmit": true,
    "baseUrl": ".",
    "sourceMap": true,
    "paths": {
      "ember-simple-auth/mixins/application-route-mixin": [
        "node_modules/ember-simple-auth/addon/mixins/application-route-mixin"
      ]
    }
  },
  "include": [
    "app/**/*"
  ]
}
```

and in routes/application.ts: 

```javascript
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
```

However, when i run `ember serve`, I get the following error in the build process:

```

/my-app/routes/application.ts(7,35): Cannot find module 'ember-simple-auth/mixins/application-route-mixin'.
/my-app/routes/application.ts(7,35): Cannot find module 'ember-simple-auth/mixins/application-route-mixin'.
```

How do I get ember-cli-typescript to correctly pick up this file?
- I should note that manually running tsc works as expected and 
- I have stopped `ember serve` and restarted after making the edits

**Comment by theseyi** [comment]
Resolved this with ambient module declaration.
http://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules
https://github.com/Microsoft/TypeScript/issues/13348#issuecomment-282388407

**Comment by chriskrycho** [comment]
Thanks, @theseyi! Next time I get ten minutes, I'll try to add this to the README.

Can you share what your actual module declaration looked like and where you put it? That'll help me (a) document it clearly for users today and (b) think about how to recommend people start building/submitting typings for other libraries as we go.

**Comment by theseyi** [comment]
Hey @chriskrycho, sure. In .d.ts file.

```typescript
// typings/ember-simple-auth/mixins/application-route-mixin.d.ts
declare module '*';
```
and included a reference path directive in the file where I had the import

```typescript
import Ember from 'ember';
/// <reference path="../typings/ember-simple-auth/mixins/application-route-mixin.d.ts" /> 
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
```
