### ISSUE TITLE
Syntax error with computed decorator

### ISSUE THREAD

**Issue by Hugo-Contreras** [emberwatch/ember-cli-typescript#46]
It looks like `ember-cli-typescript` doesn't like `computed-decorator`, I have this error on build time :
`SyntaxError: controller.js: 'return' outside of function (155:4)`

Is there any configuration specific to add ? I already put `"experimentalDecorators": true` in my `tsconfig.json`.

My code looks like that :
```
@readOnly
@computed('model.[]')
  items (model) {
    return A(model.slice());
  },
```

**Comment by QuantumInformation** [comment]
This one works for me:

https://github.com/QuantumInformation/ember-ex/blob/master/app/components/typescript-component-adv.ts#L12

**Comment by chriskrycho** [comment]
Note that you can't use the old decorator syntax, which let you decorate *object methods*; the spec as it's landing (I believe) only lets you decorate standalone functions or class methods. So you'll need to use the syntax as linked in the example above, using ES6 classes.

**Comment by Kerrick** [comment]
It's worth noting that [ember-decorators currently doesn't support Mixins](https://github.com/rwjblue/ember-decorators/issues/115), so you must use `Ember.Component.extend(MyMixin, {})` still. I understand the situation, that means there's no way to use computed decorators in a typescript file that mixes in `Ember.Mixin`s. If ember-cli-typescript still supported object method decorators, it wouldn't cause this conflict.

**Comment by chriskrycho** [comment]
Unfortunately, that support as well upstream of us: TypeScript itself doesn't support it.  And I'm not sure, but I don't think that the current version of the decorators spec does either?
