### ISSUE TITLE
How to create controller in Typescript using class syntax?

### ISSUE THREAD

**Issue by perlun** [emberwatch/ember-cli-typescript#9]
Hi,

I'm trying this addon out in https://github.com/perlun/electron-ember-typescript-example/pull/3 but am running into some problems.

I am trying do define my controller like this:

```typescript
class ApplicationController extends Ember.Controller
```

...but the problem if I then export it using `export default ApplicationController`, it's actually a proper ES2015 _class_ that gets exported. It doesn't cause any _errors_, but the constructor never runs (presumably because it must be an `_init` method instead).

If I then export it as `export default Ember.Controller.extend(ApplicationController)`, it doesn't work either.

Has anyone done this successfully, and if so, do you have a valid example? (This should be added to the wiki or README file as well)

**Comment by locks** [comment]
@perlun It is not currently possible. The Ember.js core team has plans to support `class` syntax in the near future, so we'll need to wait for that to happen :)
Thanks for trying out this addon!

**Comment by locks** [comment]
I'm closing this as this is a shortcoming of the Ember.Object object model itself. I believe that there's an issue tracking this at the Ember repo. Once again thanks for reporting!

**Comment by perlun** [comment]
@locks - thanks for the input. I looked at the Ember.js issue tracker but couldn't find any specific issue about this. Which one is it?

How do people go about implementing Ember controllers using Typescript? Just plain `Ember.Controller.extend(foo: string = "bar")` or sorts?

I think what I'm really looking for is some form of guidance. "How to write Typescript apps with Ember", best practices sort of. Yes, I know it's very early yet, but I still think it would be _incredibly_ useful to see some examples of real-world usage of this nice little `ember` addon.

(In other words: thanks for all the great effort thus far! Let's cooperate to try and make things even better in the near future.)

**Comment by chriskrycho** [comment]
@perlun I imagine you problem saw these go by at some point, but I noted this issue as I was checking things that got closed by #45, and wanted to make sure you'd seen them: I wrote up a bunch of pieces on this [on my blog](http://www.chriskrycho.com/typing-your-ember.html).

**Comment by locks** [comment]
Since this popped on my email, @perlun check https://github.com/emberjs/rfcs/pull/240 :)

**Comment by perlun** [comment]
@locks Thanks for the link, very interesting read!
@chriskrycho Thanks as well - will read the blog post you mentioned asap. Haven't really used TS + Ember since the time when I opened the issue, but maybe it's time to look into it again.
